version: '3.9'

services:
  db:
    container_name: user_segmentation_pg_db
    image: postgres:15.4-bookworm
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    env_file:
      - .env.dev

  server:
    container_name: "go_app"
    build: .
    command: ./docker/wait-for-postgres.sh db ./app
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
